[tool.pylint.MASTER]
extension-pkg-allow-list = [
    "lxml",
]

[tool.pylint.messages_control]
disable = [
  "too-few-public-methods",
  "too-many-instance-attributes",
  "too-many-public-methods",
]

[[tool.mypy.overrides]]
module = [
    "markdown.*",
    "mistune.*",
]
ignore_missing_imports = true

[tool.pyright]
pythonVersion = "3.10"
